server:
  port: 8091

spring:

  datasource:
    username: 'postgres'
    password: 'root'
    driver-class-name: org.postgresql.Driver
    url: 'jdbc:postgresql://localhost:5432/AuthDB'

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


application:
  name: auth-service-application

myapplication:
  feign:
    vehicle: http://localhost:8092/api/v1