server:
  port: 8099

spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway-service
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8091
          predicates:
            - Path= /auth/**
          filters:
            - name: CircuitBreaker
              args:
                enabled: true
                fallbackUri: forward:/fallback/authservice
        - id: vehicle-service
          uri: http://localhost:8092
          predicates:
            - Path= /vehicle/**
          filters:
            - name: CircuitBreaker
              args:
                enabled: true
                fallbackUri: forward:/fallback/vehicleservice



      default-filters:
        - RewritePath= /(?<segment>.*),/api/v1/$\{segment}