server:
  port: 80

spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway-service
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8091
          predicates:
            - Path= /api/v1/auth/**

        - id: vehicle-service
          uri: http://localhost:8092
          predicates:
            - Path= /api/v1/vehicle/**
